
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

sensor:
  - platform: rest
    name: CoffeeCherryPi
    resource: http://192.168.0.10:5000/
    
switch:
  - platform: rest
    name: 'CoffeCherry Pi Smart'
    resource: http://192.168.0.10:5000/smart/
    body_on: 'on'
    body_off: 'off'